// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocmvbjapbbqjzkezilzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbXZiamFwYmJxanprZXppbHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODE3MTIsImV4cCI6MjA1ODI1NzcxMn0.eC_eGLrNeqvRQBSU4pBG8rf1tax-vlTmJffsO1Cmewg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);